@Zadatak_HostAddress = http://localhost:5184

GET {{Zadatak_HostAddress}}/api/skills
Accept: application/json

###

GET {{Zadatak_HostAddress}}/api/candidates/search
Accept: application/json

###

GET {{Zadatak_HostAddress}}/api/candidates/search?name=Ana&skills=English
Accept: application/json

###

POST {{Zadatak_HostAddress}}/api/skills
Content-Type: application/json

{
  "name": "React"
}

###

POST {{Zadatak_HostAddress}}/api/candidates
Content-Type: application/json

{
  "fullName": "Jelena Petrovic",
  "dateOfBirth": "1998-05-12",
  "contactNumber": "+38164555666",
  "email": "jelena.petrovic@example.com",
  "skillIds": [1, 4]
}

###
